# Generated by Django 5.2 on 2025-04-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.IntegerField(blank=True, choices=[(1, 'Brasil'), (2, 'Estados Unidos')], null=True)),
            ],
        ),
    ]
