# Generated by Django 5.2 on 2025-04-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atores', '0001_initial'),
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('atores', models.ManyToManyField(blank=True, null=True, related_name='filmes', to='atores.atores')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filmes', to='genero.genero')),
            ],
        ),
    ]
